### ISSUE TITLE
P2-Project Outline - features feedback

### ISSUE THREAD

**Issue by dcmorse** [Jenellebas/liftoff-assignments#4]
Features are looking good.  Just some minor points of clarification I'd like to understand.

Surprising to me is the lack of user roles - this app will be used excursively by the ED? 

Can you explain to me why this project would be better than an Excel spreadsheet and someone with some Excel training?

Maybe consider DataTables for sorting and searching - https://datatables.net/ - it may be possible to rig up the dataables to draw from your database.

**Comment by Jenellebas** [comment]
I think you are right, the two store managers should have access as well.  Although the ED is the one who is ultimately in charge of making the decisions about which offsite sales we continue doing and which we scrap.    But the store managers do help assign volunteers to cover the events, so if I get to the point where volunteer assignment to each sale happens, they would need access as well.  

The project at this level could be done in Excel (or the Google version that is easily sharable). A feature that would take it past the Excel level:  include a map to each event (the expense of mileage with our big van isn't included or calculated at this point).  I will ponder this point!

**Comment by dcmorse** [comment]
Okay, your story submissions have assuaged my worries. I consider this issue a non-blocker to getting a 1 on this assignment.

**Comment by dcmorse** [comment]
Okay, I think this is good enough then. Consider fixing the bullet points in your outline (research markdown, or don't), then close this issue, and I'll give you a '1'.

**Comment by Jenellebas** [comment]
Hello Dave,
I'm back from vacation and slogging through all the classes I missed.  
I just edited the P2 Outline to include multiple users and google map api for expense tracking purposes.
Please let me know if there is anything else outstanding to this assignment getting a 1.

Thank you!
Jenelle
