### ISSUE TITLE
P3-Project Planning feedback

### ISSUE THREAD

**Issue by dcmorse** [Jenellebas/liftoff-assignments#5]
Nice work. Your stories and wireframes are in the right form. 

I'm happy to see your markdown skill has leveled up. 

Marking this assignment as complete - close this issue when you want.

Random pro tips:

Pro tip 1: If you promomote your github project cards into github issues, you can directly attach the wireframe images to the issue. This puts all the info in one easy-to-see place. 
Pro tip 2: you can reference github issues with hash and then id-number in other github issues. (example: #1). 
Pro tip 3: you can use the same syntax in git commit messages - example `git commit -m "fix typeo - resolves #1"`, and  when you push it to origin/master, github will automatically close the issue for you and create hyperlinks from the issue to the commit that fixes it.

**Comment by Jenellebas** [comment]
thanks for the tips!  I saw this message after I fixed and committed P2 Outline issue, so I ddin't create the hyperlink from the issue to the commit.  too late!
